import type { PlanItem, Suggestion, Survey, SurveyQuestion } from './database.types'

const id = (n: number) => `mock-${n}`

export const mockPlanItems: PlanItem[] = [
  { id: id(1), year: 2026, category: 'Gobernanza y propósito', indicator_code: 'PSG1.1.1', document_name: 'Declaración de propósito', content: 'La empresa establece una declaración de propósito que establece el impacto positivo y significativo específico que pretende tener en la sociedad o en el medio ambiente.', notes: null, responsible: 'Bel', deadline: null, status: 'trabajando', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(2), year: 2026, category: 'Gobernanza y propósito', indicator_code: 'PSG 2.1', document_name: 'Mapa de grupos de interés', content: 'La empresa dispone de un mecanismo para considerar o implicar a sus partes interesadas y representar sus intereses en la toma de decisiones.', notes: 'Talleres prospectivos. No se ha hecho anteriormente.', responsible: 'José, Carla, Bel', deadline: null, status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(3), year: 2026, category: 'Gobernanza y propósito', indicator_code: 'PSG 3.1', document_name: 'Procedimiento de quejas', content: 'La empresa cuenta con un procedimiento de quejas accesible al público que permite a las partes interesadas plantear quejas y buscar soluciones de forma segura.', notes: 'Existe buzón buzonsugerencias@xul.es. Mejor crear formulario anónimo + protocolo.', responsible: 'José, Carla, Víctor', deadline: null, status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(4), year: 2026, category: 'Gobernanza y propósito', indicator_code: 'PSG 3.2', document_name: 'Seguimiento de quejas y resumen anual', content: 'La empresa supervisa y realiza un seguimiento de las quejas y prepara resúmenes anuales sobre la situación y el objeto de las mismas.', notes: null, responsible: 'Silvia, Víctor', deadline: '2026-12-01', status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(5), year: 2026, category: 'Gobernanza y propósito', indicator_code: 'PSG 4.1', document_name: 'Política de marketing y relaciones públicas', content: 'La empresa documenta los principios que rigen sus prácticas de marketing y relaciones públicas relacionadas con las reivindicaciones medioambientales y sociales.', notes: null, responsible: 'José, Carla, Jorge', deadline: null, status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(6), year: 2026, category: 'Gobernanza y propósito', indicator_code: 'PSG 5.1', document_name: 'Acta supervisión Propósito, resultados e implementación', content: 'Al menos una vez cada 12 meses, el máximo órgano de gobierno revisa los progresos en el avance de su propósito público.', notes: 'Acta de reunión con estos temas. Organizar reunión para revisión de la memoria 2025.', responsible: 'José, Carla, Bel', deadline: '2026-06-01', status: 'trabajando', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(7), year: 2026, category: 'Trabajo justo', indicator_code: 'TJ 1', document_name: 'Contrato o carta de oferta', content: 'Todos los colaboradores tienen un contrato de trabajo o una carta de oferta que cumple los criterios de cumplimiento.', notes: null, responsible: 'Silvia', deadline: '2026-04-01', status: 'finalizado', evidence_url: 'Modelo_Condiciones Contractuales.pdf', created_at: '', updated_at: '' },
  { id: id(8), year: 2026, category: 'Trabajo justo', indicator_code: 'TJ 1.2', document_name: 'Política de horarios', content: 'La empresa tiene períodos de cancelación iguales cuando utiliza horarios variables.', notes: null, responsible: 'Silvia', deadline: '2026-05-01', status: 'pdt_revision', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(9), year: 2026, category: 'Trabajo justo', indicator_code: 'TJ 2.1', document_name: 'Política de no solicitar historiales salariales', content: 'La empresa tiene la política de no solicitar historiales salariales a los solicitantes de empleo.', notes: null, responsible: 'Silvia', deadline: '2026-05-01', status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(10), year: 2026, category: 'Trabajo justo', indicator_code: 'TJ 2.2', document_name: 'Documento sobre remuneraciones y modelo de nómina', content: 'La empresa indica a los trabajadores cómo fija su salario y a qué prestaciones tienen derecho.', notes: null, responsible: 'Silvia', deadline: '2026-05-01', status: 'pdt_revision', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(11), year: 2026, category: 'Trabajo justo', indicator_code: 'TJ 3.2', document_name: 'Encuesta de satisfacción a empleados', content: 'La empresa tiene en cuenta la opinión de los trabajadores sobre las decisiones que les afectan.', notes: 'Hecha en 2025. Lanzar a principios de junio. Automatizar el proceso añadiéndolo en la app.', responsible: 'Carla, Silvia, Elena, Víctor', deadline: '2026-06-01', status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(12), year: 2026, category: 'Trabajo justo', indicator_code: 'TJ 4.1', document_name: 'Encuesta cultura organizacional', content: 'La empresa mide periódicamente la cultura organizacional centrada en los resultados para los trabajadores.', notes: '¿Unificar con encuesta de satisfacción? > Sí, juntar preguntas', responsible: 'Carla, Silvia, Víctor, Elena', deadline: '2026-06-01', status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(13), year: 2026, category: 'JEDI', indicator_code: 'JEDI 1.1', document_name: 'Encuesta principios JEDI', content: 'La empresa ha facilitado al menos un debate o encuesta sobre los principios JEDI en el lugar de trabajo.', notes: 'Añadir en la encuesta de satisfacción.', responsible: 'Carla, Silvia, Elena, Víctor', deadline: '2026-06-01', status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(14), year: 2026, category: 'JEDI', indicator_code: 'JEDI 2.3', document_name: 'Elección y puesta en marcha de acciones JEDI', content: 'La empresa elige sus acciones JEDI utilizando datos y opiniones de las partes interesadas, las registra en un plan y las pone en práctica.', notes: 'Escoger y documentar: Una de A-E, una de F-L, una de M-S.', responsible: 'José, Carla', deadline: '2026-05-01', status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(15), year: 2026, category: 'JEDI', indicator_code: 'JEDI 2.A', document_name: 'Declaración de compromiso JEDI', content: 'La empresa se compromete públicamente con los principios de la JEDI.', notes: null, responsible: 'José, Silvia, Carla', deadline: '2026-07-01', status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(16), year: 2026, category: 'JEDI', indicator_code: 'JEDI 2.G', document_name: 'Documento de política de contratación inclusiva', content: 'La empresa aplica prácticas de contratación inclusivas.', notes: null, responsible: 'José, Carla, Silvia', deadline: '2026-07-01', status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(17), year: 2026, category: 'JEDI', indicator_code: 'JEDI 2.I', document_name: 'Guía de lenguaje inclusivo', content: 'La empresa desarrolla y aplica una guía de lenguaje inclusivo para las comunicaciones internas.', notes: null, responsible: 'Bel, Elena', deadline: '2026-07-01', status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(18), year: 2026, category: 'JEDI', indicator_code: 'JEDI 2.M', document_name: 'Web acorde a los estándares de accesibilidad', content: 'El sitio web de la empresa cumple los estándares de accesibilidad WCAG.', notes: null, responsible: 'Víctor, Aitor', deadline: '2026-07-01', status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(19), year: 2026, category: 'JEDI', indicator_code: 'JEDI 2.S', document_name: 'Participación en acción colectiva acorde a JEDI', content: 'La empresa participa en al menos una acción colectiva para hacer avanzar los principios de la JEDI.', notes: '¿Con Fundación quizás se haya hecho ya algo?', responsible: 'José', deadline: '2026-06-01', status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(20), year: 2026, category: 'Derechos humanos', indicator_code: 'DH 1.1', document_name: 'Documento público de respeto a los DDHH', content: 'La empresa se compromete públicamente a respetar los derechos humanos y los Principios Rectores de la ONU.', notes: null, responsible: 'Silvia', deadline: '2026-08-01', status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(21), year: 2026, category: 'Derechos humanos', indicator_code: 'DH 3.3', document_name: 'Proceso para evaluar impactos negativos en DDHH', content: 'La empresa evalúa los posibles impactos negativos en derechos humanos relacionados con posibles clientes y proyectos.', notes: null, responsible: null, deadline: null, status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(22), year: 2026, category: 'Derechos humanos', indicator_code: 'HR 4.2', document_name: 'Evaluación de 3 decisiones de contratación materiales', content: 'La empresa tiene en cuenta los impactos reales y potenciales sobre los derechos humanos en sus decisiones de contratación.', notes: null, responsible: 'José', deadline: '2026-10-01', status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(23), year: 2026, category: 'Acción climática', indicator_code: 'CA 2.1', document_name: 'Plan de acción por el clima en la página web', content: 'La empresa publica su plan de acción por el clima en su página web o dispone de otro medio para que las partes interesadas puedan acceder a él fácilmente.', notes: null, responsible: 'Silvia, Aitor', deadline: '2026-08-01', status: 'trabajando', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(24), year: 2026, category: 'Circularidad y gestión ambiental', indicator_code: 'ESC 1.6', document_name: 'Documento declarando que NO realizamos actividades con animales', content: 'Documento que declara que la empresa no realiza actividades relacionadas con animales.', notes: null, responsible: 'Silvia', deadline: '2026-05-01', status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(25), year: 2026, category: 'Circularidad y gestión ambiental', indicator_code: 'ESC 2.6', document_name: 'Evaluación de impactos ambientales negativos', content: 'La empresa evalúa los posibles impactos ambientales negativos relacionados con posibles clientes y proyectos.', notes: 'Revisar memoria 2025.', responsible: 'Silvia', deadline: '2026-08-01', status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(26), year: 2026, category: 'Circularidad y gestión ambiental', indicator_code: 'ESC 5.1', document_name: 'Evaluación de impactos ambientales en decisiones de contratación', content: 'La empresa tiene en cuenta los impactos ambientales reales y potenciales en sus decisiones de contratación.', notes: null, responsible: 'Silvia', deadline: '2026-09-01', status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(27), year: 2026, category: 'A. Gubernamentales y A. Colectiva', indicator_code: 'AGAC 1.1', document_name: 'Política pública de cabildeo responsable', content: 'La empresa documenta su política de cabildeo responsable incluyendo el enfoque hacia el impacto positivo social y ambiental.', notes: 'Comisión de RSE de la Conf. de Empresarios de Córdoba: José pertenece a ella.', responsible: 'José', deadline: '2026-05-01', status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(28), year: 2026, category: 'A. Gubernamentales y A. Colectiva', indicator_code: 'GACA 2.1', document_name: 'Participación en acciones colectivas', content: 'La empresa participa en acciones colectivas para avanzar en los impactos sociales o ambientales.', notes: '¿Participamos en algo relacionado? Mencionar qué y recopilarlo.', responsible: 'José', deadline: null, status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(29), year: 2026, category: 'A. Gubernamentales y A. Colectiva', indicator_code: 'GACA 2.1 A', document_name: 'Asesoramiento a empresas del sector en impacto social', content: 'La empresa asesora a otras de su sector, profesión o cadena de valor para avanzar en sus impactos sociales o ambientales.', notes: 'CECO y Vistage de José — reuniones mensuales con directivos.', responsible: 'José', deadline: null, status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(30), year: 2026, category: 'A. Gubernamentales y A. Colectiva', indicator_code: 'GACA 2.1 B', document_name: 'Contribución a la investigación para impacto social', content: 'La empresa contribuye a la investigación externa para avanzar en los impactos sociales ambientales.', notes: 'Grupos de investigación que nos piden completar encuestas del ámbito social o de impacto.', responsible: 'José', deadline: null, status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(31), year: 2026, category: 'A. Gubernamentales y A. Colectiva', indicator_code: 'GACA 2.1 C', document_name: 'Colaboración para el avance en impacto social o ambiental', content: 'La empresa colabora con múltiples partes interesadas para avanzar en los impactos sociales o ambientales.', notes: null, responsible: 'José', deadline: null, status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(32), year: 2026, category: 'A. Gubernamentales y A. Colectiva', indicator_code: 'GACA 2.1 D', document_name: 'Documento para promover políticas públicas en impacto', content: 'La empresa promueve políticas públicas para avanzar en los impactos sociales o ambientales.', notes: 'Preparar documento de la propia agencia.', responsible: 'José', deadline: null, status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
  { id: id(33), year: 2026, category: 'A. Gubernamentales y A. Colectiva', indicator_code: 'GACA 2.1 E', document_name: 'Documento liderazgo intelectual', content: 'La empresa utiliza el liderazgo intelectual para impulsar el cambio sistémico hacia una economía equitativa, inclusiva y regenerativa.', notes: 'Grupo impulsor de B Corp en Andalucía. Publicar en redes sociales.', responsible: 'José', deadline: null, status: 'no_iniciado', evidence_url: null, created_at: '', updated_at: '' },
]

export const mockSuggestions: Suggestion[] = [
  { id: 's1', type: 'internal', author_name: 'Ana García', is_anonymous: false, email: 'ana@xul.es', subject: 'Mejorar el proceso de onboarding', message: 'Creo que podríamos mejorar el proceso de incorporación de nuevos empleados con una guía más detallada y un buddy asignado durante las primeras semanas.', status: 'new', created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 's2', type: 'internal', author_name: null, is_anonymous: true, email: null, subject: 'Reuniones de equipo más cortas', message: 'Las reuniones semanales podrían ser más efectivas si tuviéramos una agenda fija y un límite de 30 minutos. Actualmente se alargan demasiado.', status: 'read', created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 's3', type: 'external', author_name: 'Pedro López', is_anonymous: false, email: 'pedro@cliente.com', subject: 'Muy buen servicio', message: 'Quería felicitar al equipo por el trabajo realizado en nuestro último proyecto. La comunicación y los resultados han superado nuestras expectativas.', status: 'resolved', created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString() },
]

export const mockSurveys: Survey[] = [
  { id: 'sv1', title: 'Encuesta de Satisfacción 2025', description: 'Encuesta anual de clima laboral y satisfacción del equipo', year: 2025, status: 'closed', created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString() },
]

export const mockSurveyQuestions: SurveyQuestion[] = [
  { id: 'q1', survey_id: 'sv1', question_text: 'En general, ¿cómo valoras tu satisfacción en XUL?', question_type: 'scale', category: 'Satisfacción', order_index: 1 },
  { id: 'q2', survey_id: 'sv1', question_text: '¿Te sientes valorado/a por tu trabajo?', question_type: 'scale', category: 'Satisfacción', order_index: 2 },
  { id: 'q3', survey_id: 'sv1', question_text: '¿Cómo valorarías tu bienestar emocional en el trabajo?', question_type: 'scale', category: 'Bienestar', order_index: 3 },
  { id: 'q4', survey_id: 'sv1', question_text: '¿Tienes un equilibrio adecuado entre vida laboral y personal?', question_type: 'scale', category: 'Bienestar', order_index: 4 },
  { id: 'q5', survey_id: 'sv1', question_text: '¿Te sientes parte del equipo y de la cultura de XUL?', question_type: 'scale', category: 'Pertenencia', order_index: 5 },
  { id: 'q6', survey_id: 'sv1', question_text: '¿Sientes que tu opinión es tenida en cuenta?', question_type: 'scale', category: 'Compromiso', order_index: 6 },
  { id: 'q7', survey_id: 'sv1', question_text: '¿Puedes expresar ideas sin miedo a represalias?', question_type: 'scale', category: 'Seguridad psicológica', order_index: 7 },
  { id: 'q8', survey_id: 'sv1', question_text: '¿Consideras que XUL promueve la diversidad, equidad e inclusión?', question_type: 'scale', category: 'JEDI', order_index: 8 },
  { id: 'q9', survey_id: 'sv1', question_text: '¿Hay algo concreto que mejorarías en XUL?', question_type: 'text', category: 'Abierta', order_index: 9 },
]

export const mockSurveyAnswers = {
  sv1: {
    totalResponses: 8,
    radarData: [
      { category: 'Satisfacción', avg: 4.1 },
      { category: 'Bienestar', avg: 3.8 },
      { category: 'Pertenencia', avg: 4.4 },
      { category: 'Compromiso', avg: 3.9 },
      { category: 'Seguridad psicológica', avg: 4.2 },
      { category: 'JEDI', avg: 4.0 },
    ],
    barData: [
      { name: 'Satisfacción general', avg: 4.1, full: 'En general, ¿cómo valoras tu satisfacción en XUL?' },
      { name: 'Me siento valorado/a', avg: 3.9, full: '¿Te sientes valorado/a por tu trabajo?' },
      { name: 'Bienestar emocional', avg: 3.8, full: '¿Cómo valorarías tu bienestar emocional en el trabajo?' },
      { name: 'Conciliación', avg: 3.6, full: '¿Tienes un equilibrio adecuado entre vida laboral y personal?' },
      { name: 'Pertenencia al equipo', avg: 4.4, full: '¿Te sientes parte del equipo y de la cultura de XUL?' },
      { name: 'Opinión valorada', avg: 3.9, full: '¿Sientes que tu opinión es tenida en cuenta?' },
      { name: 'Seguridad psicológica', avg: 4.2, full: '¿Puedes expresar ideas sin miedo a represalias?' },
      { name: 'Diversidad e inclusión', avg: 4.0, full: '¿Consideras que XUL promueve la diversidad, equidad e inclusión?' },
    ],
    textAnswers: [
      { question: '¿Hay algo concreto que mejorarías en XUL?', answers: ['Más flexibilidad horaria en ciertos periodos del año', 'Podría mejorar la comunicación entre departamentos', 'Me gustaría tener más formación interna y oportunidades de crecimiento'] },
    ],
  },
}
